In [ ]:
import pandas as pd

In [ ]:
# 1. 加载数据
df = pd.read_csv('./数据集/stock_day.csv')
df

In [ ]:
# 2. 移除不需要的列
df.drop(columns = ['ma5', 'ma10', 'ma20', 'v_ma5', 'v_ma10', 'v_ma20'], inplace = True, axis = 0)

In [ ]:
# 3. 查看详细信息
print(df)
print(df.info())
print(df.describe())

# 索引操作

In [ ]:
# 1.  直接使用行列索引获取元素（先列后行）
df['open']['2018-02-23']

In [20]:
# 2. 结合loc或者iloc使用索引获取数据
# 2.1 loc[]
df.loc['2018-02-23', 'open']
df.loc['2018-02-27':'2018-02-14', ['open', 'high']]

             open   high
2018-02-27  23.53  25.88
2018-02-26  22.80  23.78
2018-02-23  22.88  23.37
2018-02-22  22.25  22.76
2018-02-14  21.49  21.99

In [21]:
# 2.2 iloc[]
df.iloc[0, 0]
df.iloc[0:5, 0:2]

             open   high
2018-02-27  23.53  25.88
2018-02-26  22.80  23.78
2018-02-23  22.88  23.37
2018-02-22  22.25  22.76
2018-02-14  21.49  21.99